version: '3.8'

services:
  web:
    container_name: camagru-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" 
    networks:
      - app_network
    volumes:
      - php-web:/var/www/html
    depends_on:
      - db
    restart: always

  db:
    container_name: camagru-db
    image: postgres:15 
    env_file:
      - .env  
    volumes:
      - db_data:/var/lib/postgresql/data 
    networks:
      - app_network
    restart: always

  adminer:
    container_name: camagru-adminer
    image: adminer:4
    ports:
      - "8081:8080"
    networks:
      - app_network
    depends_on:
      - db
    restart: always

volumes:
  db_data:
  php-web:

networks:
  app_network:
    driver: bridge
